# Generated by Django 3.2.12 on 2022-02-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    """Django migration class to alter the id field of the user model in the database."""

    dependencies = [
        ('cryptotutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
