# Generated by Django 4.0.2 on 2022-03-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotutor', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSnippet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nicad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
