# Generated by Django 4.0.2 on 2022-05-04 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotutor', '0003_codesubmission_nicad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(default='', max_length=50)),
                ('projectLink', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('title', models.CharField(default='test', max_length=100)),
                ('points', models.IntegerField(default='0')),
                ('responseNumber', models.PositiveSmallIntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentID', models.PositiveSmallIntegerField()),
                ('studentName', models.CharField(max_length=20)),
                ('VCS', models.CharField(max_length=255)),
                ('requestedAt', models.DateTimeField()),
                ('code', models.TextField()),
                ('errType', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewerName', models.CharField(default='', max_length=255)),
                ('reviewedAt', models.DateTimeField(default='')),
                ('points', models.IntegerField(default=0)),
                ('solution', models.TextField(default='')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptotutor.question')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='studentUsername',
            field=models.TextField(default='anonymous'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='threshold',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
