# Generated by Django 4.0.2 on 2022-05-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    """Django migration class to add a views field to the question model."""


    dependencies = [
        ('cryptotutor', '0004_question_requests_responses_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
