# Generated by Django 4.0.2 on 2022-05-04 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    """Django migration class to add a createdDate field to the question model."""

    dependencies = [
        ('cryptotutor', '0005_question_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
